//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalHealth.Hl7.Common.Message {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalHealth.Hl7.Common.Message.MessageTypes", typeof(MessageTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACK.
        /// </summary>
        internal static string ACK {
            get {
                return ResourceManager.GetString("ACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADT.
        /// </summary>
        internal static string ADT {
            get {
                return ResourceManager.GetString("ADT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORM.
        /// </summary>
        internal static string ORM {
            get {
                return ResourceManager.GetString("ORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORR.
        /// </summary>
        internal static string ORR {
            get {
                return ResourceManager.GetString("ORR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORU.
        /// </summary>
        internal static string ORU {
            get {
                return ResourceManager.GetString("ORU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIU.
        /// </summary>
        internal static string SIU {
            get {
                return ResourceManager.GetString("SIU", resourceCulture);
            }
        }
    }
}
