//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalHealth.Hl7ToCdaTransformer.Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResponseStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalHealth.Hl7ToCdaTransformer.Resources.ResponseStrings", typeof(ResponseStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AUSEHR Flag has been set to an invalid value. Check the AUSEHR Flag is correct..
        /// </summary>
        internal static string AUSEHRNotValid {
            get {
                return ResourceManager.GetString("AUSEHRNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AUSEHR Flag has been set to &apos;N&apos; for this Patient indicating this Patient does not have a PCEHR..
        /// </summary>
        internal static string AUSEHRSetToN {
            get {
                return ResourceManager.GetString("AUSEHRSetToN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error in {0}, please check SystemErrorLog.
        /// </summary>
        internal static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service does not allow a patient identifier of Demographic type.
        /// </summary>
        internal static string DemographicsNotAllowedForThisService {
            get {
                return ResourceManager.GetString("DemographicsNotAllowedForThisService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ERROR) Unable to add or edit local provider.
        /// </summary>
        internal static string ErrorUnableToAddOrEditLocalProvider {
            get {
                return ResourceManager.GetString("ErrorUnableToAddOrEditLocalProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ERROR) Unable to deactivate local provider.
        /// </summary>
        internal static string ErrorUnableToDeactivateLocalProvider {
            get {
                return ResourceManager.GetString("ErrorUnableToDeactivateLocalProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An existing provider with the specified HPI-I was found..
        /// </summary>
        internal static string ExistingProviderWithHPIIFound {
            get {
                return ResourceManager.GetString("ExistingProviderWithHPIIFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HL7 message does not contain the Health Provider&apos;s Family Name. The Report cannot be uploaded..
        /// </summary>
        internal static string HealthProviderNameNotSupplied {
            get {
                return ResourceManager.GetString("HealthProviderNameNotSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Health Provider record was found for the local provider indentifier. The Report cannot be uploaded to the PCEHR.
        /// </summary>
        internal static string HealthProviderNotFound {
            get {
                return ResourceManager.GetString("HealthProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hospital was found with the given code and code system..
        /// </summary>
        internal static string HospitalNotFound {
            get {
                return ResourceManager.GetString("HospitalNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient has no MRN at the given hospital..
        /// </summary>
        internal static string HospitalPatientNotFound {
            get {
                return ResourceManager.GetString("HospitalPatientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HPI-I for this Health Provider has the wrong length and cannot be used to access the PCEHR.
        /// </summary>
        internal static string HpiiLengthNot16 {
            get {
                return ResourceManager.GetString("HpiiLengthNot16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL7 message does not contain a Health Provider&apos;s HPI-I. Document cannot be uploaded to the PCEHR.
        /// </summary>
        internal static string HpiiNotSupplied {
            get {
                return ResourceManager.GetString("HpiiNotSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Provider&apos;s HPI-I is not valid. Document cannot be uploaded to the PCEHR.
        /// </summary>
        internal static string HpiiNotValid {
            get {
                return ResourceManager.GetString("HpiiNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IHI for this patient had the wrong length and cannot be used to access the PCEHR..
        /// </summary>
        internal static string IhiLengthNot16 {
            get {
                return ResourceManager.GetString("IhiLengthNot16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IHI was found for this patient and so the PCEHR cannot be accessed..
        /// </summary>
        internal static string IhiNotSupplied {
            get {
                return ResourceManager.GetString("IhiNotSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IHI for this patient is not verified and cannot be used to access the PCEHR..
        /// </summary>
        internal static string IhiRecordStatusNotVerified {
            get {
                return ResourceManager.GetString("IhiRecordStatusNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an unresolved alert of type &apos;Demographic Mismatch&apos; for this patient. PCEHR cannot be accessed until this alert is resolved..
        /// </summary>
        internal static string IhiStatusDemographicMismatch {
            get {
                return ResourceManager.GetString("IhiStatusDemographicMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an unresolved alert of type &apos;Duplicate IHI&apos; for this patient. PCEHR cannot be accessed until this alert is resolved..
        /// </summary>
        internal static string IhiStatusDuplicateIhi {
            get {
                return ResourceManager.GetString("IhiStatusDuplicateIhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an unresolved alert of type &apos;Duplicate Patient&apos; for this patient. PCEHR cannot be accessed until this alert is resolved..
        /// </summary>
        internal static string IhiStatusDuplicatePatient {
            get {
                return ResourceManager.GetString("IhiStatusDuplicatePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IHI for this patient is expired and cannot be used to access the PCEHR..
        /// </summary>
        internal static string IhiStatusExpired {
            get {
                return ResourceManager.GetString("IhiStatusExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an unresolved alert of type &apos;Medicare/DVA Change Mismatch&apos; for this patient. PCEHR cannot be accessed until this alert is resolved..
        /// </summary>
        internal static string IhiStatusMedicareDvaChangeMismatch {
            get {
                return ResourceManager.GetString("IhiStatusMedicareDvaChangeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IHI for this patient conflicted with the IHI of another patient with which this patient was merged, and cannot be used to access the PCEHR..
        /// </summary>
        internal static string IhiStatusMergeConflict {
            get {
                return ResourceManager.GetString("IhiStatusMergeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIPS encountered an unexpected IHI status..
        /// </summary>
        internal static string IhiStatusNotHandled {
            get {
                return ResourceManager.GetString("IhiStatusNotHandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IHI for this patient is resolved and cannot be used to access the PCEHR..
        /// </summary>
        internal static string IhiStatusResolved {
            get {
                return ResourceManager.GetString("IhiStatusResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IHI for this patient is retired and cannot be used to access the PCEHR..
        /// </summary>
        internal static string IhiStatusRetired {
            get {
                return ResourceManager.GetString("IhiStatusRetired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IHI for this patient requires validation but the HI Service was not available. Please try the operation again..
        /// </summary>
        internal static string IhiStatusServiceUnavailable {
            get {
                return ResourceManager.GetString("IhiStatusServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IHI for this patient is invalid and cannot be used to access the PCEHR..
        /// </summary>
        internal static string IhiStatusUnknown {
            get {
                return ResourceManager.GetString("IhiStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sex of this patient was not recognised..
        /// </summary>
        internal static string InvalidSex {
            get {
                return ResourceManager.GetString("InvalidSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user details.
        /// </summary>
        internal static string InvalidUserDetails {
            get {
                return ResourceManager.GetString("InvalidUserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document references logo file {0} which was not supplied and there was no logo configured in the Hospital table..
        /// </summary>
        internal static string LogoNotSupplied {
            get {
                return ResourceManager.GetString("LogoNotSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisational logo for hospital {0} with size {1}x{2} pixels exceeds the 400x100 limit for uploading to PCEHR..
        /// </summary>
        internal static string LogoTooLarge {
            get {
                return ResourceManager.GetString("LogoTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing user values.
        /// </summary>
        internal static string MissingUserValues {
            get {
                return ResourceManager.GetString("MissingUserValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No patient was found with the given MRN..
        /// </summary>
        internal static string MrnNotFound {
            get {
                return ResourceManager.GetString("MrnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is more than one Ordering Provider. The document cannot be uploaded..
        /// </summary>
        internal static string MultipleOrderingProvidersExist {
            get {
                return ResourceManager.GetString("MultipleOrderingProvidersExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HL7 Message contains multiple Primary Identfiers. The Report cannot be uploaded to the PCEHR.
        /// </summary>
        internal static string MultiplePrimaryIdentifiersFound {
            get {
                return ResourceManager.GetString("MultiplePrimaryIdentifiersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of this patient was not supplied..
        /// </summary>
        internal static string NameNotSupplied {
            get {
                return ResourceManager.GetString("NameNotSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No patient was found with the given patient master identifier..
        /// </summary>
        internal static string PatientMasterIdNotFound {
            get {
                return ResourceManager.GetString("PatientMasterIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Patients PCEHR has not been advertised or disclosed. The Report cannot be uploaded..
        /// </summary>
        internal static string PCEHRNotDisclosed {
            get {
                return ResourceManager.GetString("PCEHRNotDisclosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No patient was found with the given enterprise patient identifier..
        /// </summary>
        internal static string StatePatientIdNotFound {
            get {
                return ResourceManager.GetString("StatePatientIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The admission at {0} for the patient {1} at {2} could not be found.  Check that this is the correct Patient Identifier..
        /// </summary>
        internal static string UnableToGetEpisode {
            get {
                return ResourceManager.GetString("UnableToGetEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database access failed when populating the list of hospitals..
        /// </summary>
        internal static string UnableToGetHospitalList {
            get {
                return ResourceManager.GetString("UnableToGetHospitalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database access failed when retrieving patient record..
        /// </summary>
        internal static string UnableToGetPatientMaster {
            get {
                return ResourceManager.GetString("UnableToGetPatientMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database access failed when creating patient record..
        /// </summary>
        internal static string UnableToInsertPatientStub {
            get {
                return ResourceManager.GetString("UnableToInsertPatientStub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database access failed when populating the list of local providers..
        /// </summary>
        internal static string UnableToListLocalProviders {
            get {
                return ResourceManager.GetString("UnableToListLocalProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A patient identifier of unknown type was supplied..
        /// </summary>
        internal static string UnknownPatientIdentifierType {
            get {
                return ResourceManager.GetString("UnknownPatientIdentifierType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vistor Hospital for hospital code {0} with HospitalId {1} not found..
        /// </summary>
        internal static string VisitorHospitalNotFound {
            get {
                return ResourceManager.GetString("VisitorHospitalNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Hospital for hospital code {0} with code system {1} not found..
        /// </summary>
        internal static string VisitorHospitalNotFoundByCode {
            get {
                return ResourceManager.GetString("VisitorHospitalNotFoundByCode", resourceCulture);
            }
        }
    }
}
