//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalHealth.Hl7ToCdaTransformer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConstantsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstantsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalHealth.Hl7ToCdaTransformer.Resources.ConstantsResource", typeof(ConstantsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find hospital with code {0} in code system {1}.
        /// </summary>
        internal static string CannotFindHospital {
            get {
                return ResourceManager.GetString("CannotFindHospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find patient with MRN {0} in Hospital {1}.
        /// </summary>
        internal static string CannotFindPatient {
            get {
                return ResourceManager.GetString("CannotFindPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} {3} {4} {5}.
        /// </summary>
        internal static string ContactDetailsFormat {
            get {
                return ResourceManager.GetString("ContactDetailsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error in {0}, please check SystemErrorLog.
        /// </summary>
        internal static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received DOB {0:dd/MM/yyyy} differs from current DOB {1:dd/MM/yyyy}..
        /// </summary>
        internal static string DateOfBirthMismatchError {
            get {
                return ResourceManager.GetString("DateOfBirthMismatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth {0:dd/MM/yyyy} out of range..
        /// </summary>
        internal static string DateOfBirthOutOfRange {
            get {
                return ResourceManager.GetString("DateOfBirthOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        internal static string DefaultAddressTypeCode {
            get {
                return ResourceManager.GetString("DefaultAddressTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1101.
        /// </summary>
        internal static string DefaultCountryCode {
            get {
                return ResourceManager.GetString("DefaultCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise merge of {0} into {1} failed.
        /// </summary>
        internal static string EnterpriseMergeFailed {
            get {
                return ResourceManager.GetString("EnterpriseMergeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neither patient was found for enterprise merge from {0} to {1}.
        /// </summary>
        internal static string EnterpriseMergeNeitherFound {
            get {
                return ResourceManager.GetString("EnterpriseMergeNeitherFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the survivor was found for enterprise merge from {0} to {1}.
        /// </summary>
        internal static string EnterpriseMergeOnlySurvivorFound {
            get {
                return ResourceManager.GetString("EnterpriseMergeOnlySurvivorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise merge of {0} into new {1} failed.
        /// </summary>
        internal static string EnterpriseMergeToNewIdFailed {
            get {
                return ResourceManager.GetString("EnterpriseMergeToNewIdFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ERROR) HIPS failed while processing HL7 message {0} from {1} at {2}.
        /// </summary>
        internal static string ErrorMessageHipsFailed {
            get {
                return ResourceManager.GetString("ErrorMessageHipsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ERROR) HPI-I lookup failed for HL7 message {0} from {1} at {2}.
        /// </summary>
        internal static string ErrorMessageHpiiLookupFail {
            get {
                return ResourceManager.GetString("ErrorMessageHpiiLookupFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ERROR) IHI lookup failed for HL7 message {0} from {1} at {2}.
        /// </summary>
        internal static string ErrorMessageIhiLookupFail {
            get {
                return ResourceManager.GetString("ErrorMessageIhiLookupFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Hips Exception Message was received. Message: {0}. Details: {1}..
        /// </summary>
        internal static string HipsExceptionMessage {
            get {
                return ResourceManager.GetString("HipsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital not found with identifier {0} from {1}..
        /// </summary>
        internal static string HospitalNotFoundError {
            get {
                return ResourceManager.GetString("HospitalNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IHI in the HL7 message has a Status other than Active set.
        /// </summary>
        internal static string IhiNotInActiveStatus {
            get {
                return ResourceManager.GetString("IhiNotInActiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IHI validation period in the HL7 message has expired.
        /// </summary>
        internal static string IhiValidationPeriodExpired {
            get {
                return ResourceManager.GetString("IhiValidationPeriodExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL7 message contains an incorrect Test Result Status.
        /// </summary>
        internal static string IncorrectTestResultStatusSupplied {
            get {
                return ResourceManager.GetString("IncorrectTestResultStatusSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (INFO) HL7 PID Segment of MRN {0} at {1} has an Invalid Date Of Death..
        /// </summary>
        internal static string InfoMessageDateOfDeathBeforeSQLDateMin {
            get {
                return ResourceManager.GetString("InfoMessageDateOfDeathBeforeSQLDateMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DateOfDeath received as {0} : stored DateOfDeath as {1:dd/MM/yyyy} and DateOfDeath Indicator set to {2}.
        /// </summary>
        internal static string InfoMessageDateOfDeathBeforeSQLDateMinEx {
            get {
                return ResourceManager.GetString("InfoMessageDateOfDeathBeforeSQLDateMinEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (INFO) IHI lookup failed for HL7 message {0} from {1} at {2}.
        /// </summary>
        internal static string InfoMessageIhiLookupFail {
            get {
                return ResourceManager.GetString("InfoMessageIhiLookupFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (INFO) HL7 message {0} from {1} at {2} was not processed.
        /// </summary>
        internal static string InfoMessageNotProcessed {
            get {
                return ResourceManager.GetString("InfoMessageNotProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient precision in date of birth.
        /// </summary>
        internal static string InsufficientPrecisionInDateOfBirth {
            get {
                return ResourceManager.GetString("InsufficientPrecisionInDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth {0} is not a valid date/time..
        /// </summary>
        internal static string InvalidDateOfBirth {
            get {
                return ResourceManager.GetString("InvalidDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data in IHI request: MRN {0} at {1}, DOB {2:dd/MM/yyyy}, stored DOB {3:dd/MM/yyyy}.
        /// </summary>
        internal static string InvalidIhiRequest {
            get {
                return ResourceManager.GetString("InvalidIhiRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL7 message contains an invalid Observation Date and Time.
        /// </summary>
        internal static string InvalidObservationDateTime {
            get {
                return ResourceManager.GetString("InvalidObservationDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL7 message contains an invalid Test Result Date and Time.
        /// </summary>
        internal static string InvalidResultsDateTime {
            get {
                return ResourceManager.GetString("InvalidResultsDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user details.
        /// </summary>
        internal static string InvalidUserDetails {
            get {
                return ResourceManager.GetString("InvalidUserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received last name {0} differs from current last name {1}..
        /// </summary>
        internal static string LastNameMismatchError {
            get {
                return ResourceManager.GetString("LastNameMismatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source patient not found for merge MRN {0} into {1}.
        /// </summary>
        internal static string MergeMrnSourceNotFound {
            get {
                return ResourceManager.GetString("MergeMrnSourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source episode not found for merge visit {0} into {1} for MRN {2}.
        /// </summary>
        internal static string MergeVisitSourceEpisodeNotFound {
            get {
                return ResourceManager.GetString("MergeVisitSourceEpisodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source patient not found for merge visit {0} into {1} for MRN {2}.
        /// </summary>
        internal static string MergeVisitSourcePatientNotFound {
            get {
                return ResourceManager.GetString("MergeVisitSourcePatientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL7 message {0} from {1} at {2} failed.
        /// </summary>
        internal static string MessageFailedFormat {
            get {
                return ResourceManager.GetString("MessageFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL7 message {0} from {1} at {2} needs retry.
        /// </summary>
        internal static string MessageNeedsRetryFormat {
            get {
                return ResourceManager.GetString("MessageNeedsRetryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL7 message {0} from {1} at {2} was skipped.
        /// </summary>
        internal static string MessageSkippedFormat {
            get {
                return ResourceManager.GetString("MessageSkippedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source patient not found for move MRN {0} to enterprise ID {1}.
        /// </summary>
        internal static string MoveMrnSourceNotFound {
            get {
                return ResourceManager.GetString("MoveMrnSourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode not found for move visit {0} from {1} to {2}.
        /// </summary>
        internal static string MoveVisitEpisodeNotFound {
            get {
                return ResourceManager.GetString("MoveVisitEpisodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move visit {0} from {1} to {2} failed.
        /// </summary>
        internal static string MoveVisitFailed {
            get {
                return ResourceManager.GetString("MoveVisitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source patient not found for move visit {0} from {1} to {2}.
        /// </summary>
        internal static string MoveVisitSourcePatientNotFound {
            get {
                return ResourceManager.GetString("MoveVisitSourcePatientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple episodes exists for the Filler Order Number(s).
        /// </summary>
        internal static string MultipleEpisodesForFillerOrderNumber {
            get {
                return ResourceManager.GetString("MultipleEpisodesForFillerOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No date of birth for patient.
        /// </summary>
        internal static string NoDateOfBirthForPatient {
            get {
                return ResourceManager.GetString("NoDateOfBirthForPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL7 message does not contain an Examination Procedure details.
        /// </summary>
        internal static string NoExaminationProcedureDetails {
            get {
                return ResourceManager.GetString("NoExaminationProcedureDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL7 message does not contain an IHI for the patient.
        /// </summary>
        internal static string NoIhiForPatient {
            get {
                return ResourceManager.GetString("NoIhiForPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL7 message does not contain a Legal Name for the patient.
        /// </summary>
        internal static string NoLegalNameForPatient {
            get {
                return ResourceManager.GetString("NoLegalNameForPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL7 message does not contain a Medicare or DVA number..
        /// </summary>
        internal static string NoMedicareOrDvaNumberForPatient {
            get {
                return ResourceManager.GetString("NoMedicareOrDvaNumberForPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL7 message does not contain an MRN for the patient.
        /// </summary>
        internal static string NoMrnForPatient {
            get {
                return ResourceManager.GetString("NoMrnForPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL7 message does not contain a Ordering Provider.
        /// </summary>
        internal static string NoOrderingProviderDetails {
            get {
                return ResourceManager.GetString("NoOrderingProviderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL7 message does not contain a Test Result Name.
        /// </summary>
        internal static string NoTestResultNameSupplied {
            get {
                return ResourceManager.GetString("NoTestResultNameSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL7 message does not contain a Test Result Status.
        /// </summary>
        internal static string NoTestResultStatusSupplied {
            get {
                return ResourceManager.GetString("NoTestResultStatusSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL7 message does not contain a visit number for the episode.
        /// </summary>
        internal static string NoVisitNumberForEpisode {
            get {
                return ResourceManager.GetString("NoVisitNumberForEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to labFacCd.
        /// </summary>
        internal static string PathologyHospitalCodeSystem {
            get {
                return ResourceManager.GetString("PathologyHospitalCodeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pasFacCd.
        /// </summary>
        internal static string PatientAdministrationSystemHospitalCodeSystem {
            get {
                return ResourceManager.GetString("PatientAdministrationSystemHospitalCodeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Patient does not match the Patient with the existing Filler Order Number(s).
        /// </summary>
        internal static string PatientNotMatchedToFillerOrderNumber {
            get {
                return ResourceManager.GetString("PatientNotMatchedToFillerOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient not yet registered.
        /// </summary>
        internal static string PatientNotYetRegistered {
            get {
                return ResourceManager.GetString("PatientNotYetRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to patientIdAuthCd.
        /// </summary>
        internal static string PrimaryPatientIdentifierCodeSystem {
            get {
                return ResourceManager.GetString("PrimaryPatientIdentifierCodeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatePatientId for {0} at {1} changed from {2} to {3}.
        /// </summary>
        internal static string StatePatientIdentifierChange {
            get {
                return ResourceManager.GetString("StatePatientIdentifierChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled HL7 message type: {0}.
        /// </summary>
        internal static string Unhandled_HL7_Message_Type {
            get {
                return ResourceManager.GetString("Unhandled_HL7_Message_Type", resourceCulture);
            }
        }
    }
}
